changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Quebram compatibilidade Breaking Changes  🛠
      labels:
        - breaking-change
    - title: Novas funcionalidades New Features 🎉
      labels:
        - feature
    - title: Melhorias 🎉
      labels:
        - enhancement
    - title: Correções Bug Fixes 🐛
      labels:
        - bug
        - fix
    - title: Outras mudanças
      labels:
        - "*"
