def format_response(
    title,
    parent,
    parent_id,
    parent_article_type,
    parent_lang,
    item,
    sub_item,
    validation_type,
    is_valid,
    expected,
    obtained,
    advice,
    data,
    error_level,
):
    return {
        'title': title,
        'parent': parent,
        'parent_id': parent_id,
        'parent_article_type': parent_article_type,
        'parent_lang': parent_lang,
        'item': item,
        'sub_item': sub_item,
        'validation_type': validation_type,
        'response': 'OK' if is_valid else error_level,
        'expected_value': expected,
        'got_value': obtained,
        'message': f'Got {obtained}, expected {expected}',
        'advice': None if is_valid else advice,
        'data': data,
    }
